# Generated by Django 4.2.6 on 2023-10-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='phone_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='user_name',
            new_name='username',
        ),
    ]
