# Generated by Django 4.2.6 on 2023-10-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_rename_phone_number_userdetails_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='is_doctor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
