# Generated by Django 4.2.6 on 2023-10-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0005_remove_userdetails_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='is_doctor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
