# Generated by Django 4.2.6 on 2023-10-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0018_alter_doctorprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='hostipal',
            new_name='hospital',
        ),
    ]
