# Generated by Django 4.2.6 on 2023-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0021_alter_userdetails_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
