# Generated by Django 4.2.6 on 2023-11-02 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0022_alter_doctorprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='doctor_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_app.doctorprofile'),
        ),
    ]
