# Generated by Django 4.2.6 on 2023-11-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0023_userdetails_doctor_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='doctor_profile',
        ),
    ]
